---
apiVersion: v1
kind: Service
metadata:
  name: web-monitoring-svc
  labels:
    app: web-monitoring
    prometheus: default
spec:
  type: NodePort
  selector:
    app: web-monitoring
  ports:
  - name: web
    protocol: TCP
    port: 80
    nodePort: 30080
  - name: metrics
    protocol: TCP
    port: 9113
    nodePort: 30113